/**
 * When we wrap errors, an Error always prefixes the toString() and stack with
 * "Error: ", so we can remove that prefix.
 */
export declare function tryEach(arr: (() => void)[]): void;
export declare function cleanError(s: any): string;
export declare function asError(err: any): Error;
